# SPDX-License-Identifier: BSD-2-Clause
# FreeBSD 16 demo image for Aeolus — nextcloud
ARG BASE=ghcr.io/freebsd/freebsd-runtime:16.snap
FROM ${BASE}
ARG packages=nextcloud-php85
RUN pkg install -y ${packages} && pkg clean -ay
