# SPDX-License-Identifier: BSD-2-Clause
# FreeBSD 16 demo image for Aeolus — emby-server
ARG BASE=ghcr.io/freebsd/freebsd-runtime:16.snap
FROM ${BASE}
ARG packages=emby-server
RUN pkg install -y ${packages} && pkg clean -ay
